name: Build and Deploy doc

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Mark github workspace as safe
      run: git config --global --add safe.directory /github/workspace
    - name: Build only 
      uses: shalzz/zola-deploy-action@v0.16.1
      env:
        BUILD_DIR: ./doc
        BUILD_ONLY: true
    - name: Build crate doc
      run: cargo doc --workspace --document-private-items --all-features -r
    - name: Tree
      run: tree -L 3
    - name: Move crate doc
      run: sudo mv ./target/doc/* ./doc/public/
    - name: Tree
      run: tree -L 4
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './doc/public'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1